### ISSUE TITLE
Step 2: Exception in thread "main" overflowdb.storage.BackwardsCompatibilityError

### ISSUE THREAD

**Issue by Ricardo1998-Xu** [VulCNN/VulCNN#23]
When generating pdgs, it doesn't generate .dot files, but folders one by one, and also generates the following error, help!

Exception in thread "main" overflowdb.storage.BackwardsCompatibilityError: storage metadata does not contain version number, this must be an old format.
	at overflowdb.storage.OdbStorage.verifyStorageVersion(OdbStorage.java:100)
	at overflowdb.storage.OdbStorage.<init>(OdbStorage.java:62)
	at overflowdb.storage.OdbStorage.createWithSpecificLocation(OdbStorage.java:54)
	at overflowdb.Graph.<init>(Graph.java:72)
	at overflowdb.Graph.open(Graph.java:53)
	at io.shiftleft.codepropertygraph.generated.Cpg$.withConfig(Cpg.scala:33)
	at io.shiftleft.codepropertygraph.Cpg$.withConfig(Cpg.scala:34)
	at io.shiftleft.codepropertygraph.cpgloading.CpgLoader.loadFromOverflowDb(CpgLoader.scala:83)
	at io.shiftleft.codepropertygraph.cpgloading.CpgLoader$.loadFromOverflowDb(CpgLoader.scala:36)
	at io.joern.joerncli.CpgBasedTool$.loadFromOdb(CpgBasedTool.scala:21)
	at io.joern.joerncli.JoernExport$.$anonfun$main$1(JoernExport.scala:66)
	at io.joern.joerncli.JoernExport$.$anonfun$main$1$adapted(JoernExport.scala:61)
	at scala.Option.foreach(Option.scala:437)
	at io.joern.joerncli.JoernExport$.main(JoernExport.scala:61)
	at io.joern.joerncli.JoernExport.main(JoernExport.scala)

**Comment by Byw111** [comment]
请问您解决了嘛，我也遇到了这个问题

**Comment by Ricardo1998-Xu** [comment]
> 请问您解决了嘛，我也遇到了这个问题

还没有解决
